try:
    raise Exception('test exception')
except Exception as e:
    print('exception message: ' + str(e))


# python raising_exceptions.py


